AWSTemplateFormatVersion: '2010-09-09'

Transform: Count

Parameters:

  TestCount:
    Type: Number
    Default: 3

  TestList:
    Type: CommaDelimitedList
    Default: 'foo,bar'

Resources:

  BucketToCopyA:
    Type: AWS::S3::Bucket
    Count: 3
    Properties:
      Tags:
        - Key: TestKey
          Value: 'my bucket %d'

  BucketToCopyB:
    Type: AWS::S3::Bucket
    Count: ['foo', 'bar']
    Properties:
      Tags:
        - Key: TestKey
          Value: 'my %s bucket %d'

  BucketToCopyC:
    Type: AWS::S3::Bucket
    Count: !Ref TestCount
    Properties:
      Tags:
        - Key: TestKey
          Value: 'my bucket %d'

  BucketToCopyD:
    Type: AWS::S3::Bucket
    Count: !Ref TestList
    Properties:
      Tags:
        - Key: TestKey
          Value: 'my %s bucket %d'
