AWSTemplateFormatVersion: "2010-09-09"
Description: Deploy a Lambda custom resource for Cloudformation to update KMS key Policies
Parameters:
  ParamS3Bucket:
    Description: The S3 Bucket that holds the lambda code
    Type: String
  ParamS3Key:
    Description: The S3 key for the lambda code zip file
    Type: String
Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudFormationRead
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:DescribeStacks
                Resource: !Sub "arn:aws:cloudformation:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: AllowLambdaToWriteLogs
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/*:*"
              - Sid: AllowLambdaToCreateLogGroups
                Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                Resource: !Sub "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*"
        - PolicyName: KMSPolicyUpdate
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - kms:GetKeyPolicy
                  - kms:PutKeyPolicy
                # WARNING
                # Lock this Resource down when deploying in a real environment
                Resource: '*'
      RoleName: !Sub "KMS-Key-Policy-Updater-${AWS::StackName}"
      Path:
        Fn::Sub: /
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref ParamS3Bucket
        S3Key: !Ref ParamS3Key
      Description: 'Custom CloudFormation resource to update a KMS Key Policy'
      FunctionName: !Sub "KMS-Key-Policy-Updater-${AWS::StackName}"
      Handler: 'lambda_function.lambda_handler'
      MemorySize: 128
      Role:
        Fn::GetAtt: LambdaRole.Arn
      Runtime: python2.7
      Timeout: 60
Outputs:
  LambdaFunctionARN:
    Description: The ARN of the lambda function
    Value:
      !GetAtt LambdaFunction.Arn
    Export:
      Name: 'KMSKeyPolicyUpdater'
